name: Build thesis.pdf

on:
  push:
    paths:
      - '**/*.tex'
  pull_request:
    paths:
      - '**/*.tex'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install TeX Live
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-full

    - name: Compile LaTeX
      run: |
        latexmk -pdf -interaction=nonstopmode -halt-on-error template/thesis.tex

    - name: Upload PDF
      uses: ./github/actions/upload-artifact
      with:
        name: thesis-pdf
        path: template/thesis.pdf
