name: Build thesis.pdf

on:
  push:
    paths:
      - '**/*.tex'
      - '**/*.cls'
      - '**/*.bib'
  pull_request:
    paths:
      - '**/*.tex'
      - '**/*.cls'
      - '**/*.bib'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: List files before compilation
      run: ls -R template/
    
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compile LaTeX
      uses: xu-cheng/latex-action@v3
      with:
        root_file: template/thesis.tex
        working_directory: .

    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: thesis-pdf
        path: template/thesis.pdf
